apiVersion: v1
kind: Service
metadata:
  name: air-workflow1
  namespace: sample-app-namespace-1752592910908
  labels:
    app.kubernetes.io/name: air-workflow1
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: air-workflow1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000