apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow1-config
  namespace: sample-app-namespace-1765564241938
  labels:
    app.kubernetes.io/name: workflow1
    kubernetes.azure.com/generator: devhub
data: