apiVersion: v1
kind: Service
metadata:
  name: workflow1
  namespace: sample-app-namespace-1765564241938
  labels:
    app.kubernetes.io/name: workflow1
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: workflow1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80