apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ca-workflow3
  labels:
    app.kubernetes.io/name: ca-workflow3
    app.kubernetes.io/part-of: ca-workflow3-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: ca-workflow3